### ISSUE TITLE
Не выкидывает исключение с отрицательным начальным балансом

### ISSUE THREAD

**Issue by KaterinaVoroshilova** [KaterinaVoroshilova/JAVA-DIPLOM#1]
# Описание
При создании кредитного счета с отрицательным начальным балансом не выкидывает исключение IllegalArgumentException

# Локация дефекта
https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/blob/a9d5f27f37c484918af6da10c2f2f1b2991e248c/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19-L23

# Шаги воспроизведения

1. Создать объект класса CreditAccount с отрицательным initialBalance
2. Запустить в программу
3. Посмотреть на вывод в консоли

*Ожидаемый результат:* Вывод сообщения "Начальный баланс не может быть отрицательным"
*Фактический результат:* Тест падает, сообщение в консоли об ошибке

# Скриншот
![image](https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/assets/137503847/281fc92c-5ed9-477f-9fdc-6373a5d76f76)

# Тест
https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/blob/a9d5f27f37c484918af6da10c2f2f1b2991e248c/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L22-L32

# Окружение
* **Операционная система:** Windows 10 Домашняя версия 22H2
* **IDE:** IntelliJ IDEA Community Edition 2023.1.4
* **Java:** OpenJDK 11.0.19

@gatsu00

**Comment by gatsu00** [comment]
Исправлено
