### ISSUE TITLE
Передача отрицательного начального баланса

### ISSUE THREAD

**Issue by gatsu00** [KaterinaVoroshilova/JAVA-DIPLOM#10]
# Описание
При создании сберегательного счета с отрицательным начальным балансом не возникает исключение по условию.

# Локация деффекта
https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/blob/e586503fa99cdd2cb60383fdf80304abc0fbd9e4/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22-L32

# Шаги воспроизведения
1. Создать объект класса SavingAccountTest с отрицательным начальным балансом initialBalance
2. Запустить в программу
3. Посмотреть на вывод в консоли

* Ожидаемый результат: * Вывод сообщения: " Начальный баланс не может быть отрицательным"
* Фактический результат: * Тест прерывается с сообщением об ошибке в консоли

# Скриншот
![image](https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/assets/137397543/1cb2fc20-f4ee-431b-b876-8275e9b0c836)

# Тест
https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/blob/3836bbaa2b4752260944bc53531ca8de4b22565f/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L64-L74

# Окружение
* **Операционная система:** Windows 10 Pro 21H2
* **IDE:** IntelliJ IDEA 2023.1.4 (Community Edition)
*  **Java: **  OpenJDK 11

**Comment by KaterinaVoroshilova** [comment]
исправлено
