### ISSUE TITLE
начальный баланс превышает максимальный

### ISSUE THREAD

**Issue by gatsu00** [KaterinaVoroshilova/JAVA-DIPLOM#11]
# Описание
При создании сберегательного счета с начальным балансом(initialBalance) превышающего максимальный(maxBalance) не вызывает исключение при запуске

# Локация дефекта
https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/blob/3836bbaa2b4752260944bc53531ca8de4b22565f/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22-L27

# Шаги воспроизведения
1. Создать объект класса SavingAccount с начальным балансом превышающего максимальный
2. Запустить программу
3. Посмотреть на вывод в консоли

*Ожидаемый результат:* Вывод сообщения: "Начальный баланс не может быть больше максимального баланса"
*Фактический результат:* Тест прерывается с сообщением об ошибке в консоли

# Скриншот
![image](https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/assets/137397543/4bfc08da-0f9d-4b14-8f71-e094c290e982)

# Тест
https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/blob/81038336adebe7ee2aceb7be0b6f2babdeac1a5a/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L80-L90

* **Операционная система:** Windows 10 Pro 21H2
* **IDE:** IntelliJ IDEA 2023.1.4 (Community Edition)
* **Java:** OpenJDK 11.0.19

**Comment by KaterinaVoroshilova** [comment]
исправлено
