### ISSUE TITLE
при списании, баланс становится отрицательным

### ISSUE THREAD

**Issue by gatsu00** [KaterinaVoroshilova/JAVA-DIPLOM#12]
# Описание
Ожидается, что при операции списания на 200 единиц счета, метод pay() не должен изменять текущий баланс, и ожидается, что значение баланса будет равно 100. Однако фактический результат показывает, что значение баланса становится отрицательным (-100).

# Локация дефекта
https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/blob/8312fedb80ef5e8478f9b53aecc6f3e5c0fc99a0/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L43-L54

# Шаги воспроизведения
1.  Создать экземпляр класса SavingAccount с параметрами:
   Текущий баланс: 100
   Минимальный баланс: 50
   Максимальное значение баланса: 500
   Процентная ставка: 5
2. Вызвать метод `pay(200)` для выполнения операции списания на 200 единиц.

*Ожидаемый результат:*  Ожидается, что значение баланса будет равно 100.
*Фактический результат:* Фактическое значение баланса становится отрицательным (-100).

# Скриншот
![image](https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/assets/137397543/7111657d-1a77-4d09-8d1e-8db7d09cc513)

# Тест
https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/blob/a487242728ad4ca7dc8aea828cb069f19099eea9/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L64-L75

* **Операционная система:** Windows 10 Pro 21H2
* **IDE:** IntelliJ IDEA 2023.1.4 (Community Edition)
* **Java:** OpenJDK 11.0.19

**Comment by KaterinaVoroshilova** [comment]
исправлено
