### ISSUE TITLE
Минимальный баланс равен максимальному балансу

### ISSUE THREAD

**Issue by gatsu00** [KaterinaVoroshilova/JAVA-DIPLOM#15]
# Описание
При создании экземпляра класса SavingAccount, минимальный баланс может быть установлен равным максимальному балансу. 

# Локация дефекта
https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/blob/a487242728ad4ca7dc8aea828cb069f19099eea9/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22-L27

# Шаги воспроизведения:
1. Создать объект SavingAccount со следующими параметрами:
   Начальный баланс: 100
   Минимальный баланс: 500
   Максимальный баланс: 500
   Процентная ставка: 5
2. Запустить программу с тестом
3. Посмотреть на вывод в консоли

*Фактический результат:* Вывод сообщения: " Минимальный баланс не может быть равен максимальному"
*Ожидаемый результат:* Тест прерывается с сообщением об ошибке в консоли

# Скриншот
![image](https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/assets/137397543/0f47ab4f-d70b-45ea-8baa-453b6d1d9630)

# Тест
https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/blob/0c7c7a934099676ee023e26c67fb168f096e4fad/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L78-L86

# Окружение
* **Операционная система:** Windows 10 Pro 21H2
* **IDE:** IntelliJ IDEA 2023.1.4 (Community Edition)
* **OpenJDK 11:** OpenJDK 11

**Comment by KaterinaVoroshilova** [comment]
исправлено
