### ISSUE TITLE
не учитывает начальный баланс при пополнении

### ISSUE THREAD

**Issue by gatsu00** [KaterinaVoroshilova/JAVA-DIPLOM#18]
# Описание
При пополнении баланса указывает только сумму пополнения, не учитывая начальный баланс 

#Локация дефекта
https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/blob/4974b3b6080f2f9bea6a5d8594a5e6f2e1846a26/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L72-L76

# Шаги воспроизведения
1. Создать экземпляр класса SavingAccount с следующими параметрами:
   Начальный баланс: 3_000
   Минимальный баланс: 3_000
   Максимальный баланс: 6_000
   Процентная ставка: 5
2. Запустить метод add(2_000) для созданного экземпляра счета.

*Ожидаемый результат:* 5_000
*Фактический результат:* 2_000

# Скриншот
![image](https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/assets/137397543/a241920e-3c66-49be-a766-a9ce47bfcf95)

# Тест
https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/blob/37d6f50f1d8614cdc8b19b3d3ed600f3d5135405/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L64-L76

# Окружение
* **Операционная система:** Windows 10 Pro 21H2
*  **IDE:** IntelliJ IDEA 2023.1.4 (Community Edition)
*  **Java:** OpenJDK 11

**Comment by KaterinaVoroshilova** [comment]
исправлено
