### ISSUE TITLE
не выкидывает исключение при отрицательном максимальном балансе

### ISSUE THREAD

**Issue by gatsu00** [KaterinaVoroshilova/JAVA-DIPLOM#23]
# Описание
При создании сберегательного счета с отрицательным максимальным балансом не возникает исключение по условию.

#Локация дефекта
https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/blob/e586503fa99cdd2cb60383fdf80304abc0fbd9e4/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19-L28

# Шаги воспроизведения
1. Создать объект класса SavingAccount с отрицательным максимальным балансом MaxBalance
2. Запустить в программу
3. Посмотреть на вывод в консоли

*Ожидаемый результат:* Вывод сообщения: " Максимальный баланс не может быть отрицательным"
*Фактический результат:*Тест прерывается с сообщением об ошибке в консоли

# Скриншот
![image](https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/assets/137397543/acd8f14d-3d48-4e3a-bf9c-05290bb784bd)

# Тест
https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/blob/81038336adebe7ee2aceb7be0b6f2babdeac1a5a/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L32-L42

# Окружение
* **Операционная система:** Windows 10 Pro 21H2
*  **IDE:** IntelliJ IDEA 2023.1.4 (Community Edition)
*  **Java:** OpenJDK 11

**Comment by KaterinaVoroshilova** [comment]
исправлено
