### ISSUE TITLE
не выкидывает исключение при начальном балансе меньше минимального 

### ISSUE THREAD

**Issue by gatsu00** [KaterinaVoroshilova/JAVA-DIPLOM#27]
# Описание
При создании сберегательного счета с начальным балансом меньше минимального баланса не возникает исключение по условию.

#Локация дефекта
https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/blob/81038336adebe7ee2aceb7be0b6f2babdeac1a5a/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22-L32

# Шаги воспроизведения
1. Создать объект класса SavingAccount с начальным балансом меньше минимального 
2. Запустить в программу
3. Посмотреть на вывод в консоли

*Ожидаемый результат:* Вывод сообщения: " Начальный баланс не может быть меньше минимального"
*Фактический результат:* Тест прерывается с сообщением об ошибке в консоли

# Скриншот
![image](https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/assets/137397543/4bd3be71-339f-498e-9651-6fe9a882c3bb)

# Тест
https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/blob/81038336adebe7ee2aceb7be0b6f2babdeac1a5a/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L68-L79

# Окружение
* **Операционная система:** Windows 10 Pro 21H2
*  **IDE:** IntelliJ IDEA 2023.1.4 (Community Edition)
*  **Java:** OpenJDK 11

**Comment by KaterinaVoroshilova** [comment]
исправлено
