### ISSUE TITLE
не выкидывает true при оплате равной лимиту минимального баланса

### ISSUE THREAD

**Issue by gatsu00** [KaterinaVoroshilova/JAVA-DIPLOM#28]
# Описание
При списании баланса выдает false, хотя мы остаемся в минимальном лимите

#Локация дефекта
https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/blob/81038336adebe7ee2aceb7be0b6f2babdeac1a5a/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L43-L54

# Шаги воспроизведения
1. Создать экземпляр класса SavingAccount с следующими параметрами:
   - Начальный баланс: 1_000
   - Минимальный баланс: 0
   - Максимальный баланс: 10_000
   - Процентная ставка: 15
2. Запустить Assertions.assertEquals(true, account.pay(1000));

*Ожидаемый результат:* true(покупка совершенна)
*Фактический результат:* false(покупка не совершена)

# Скриншот
![image](https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/assets/137397543/136e9513-3f31-496e-ad05-b61fddf4245a)

# Тест
https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/blob/81038336adebe7ee2aceb7be0b6f2babdeac1a5a/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L128-L138

# Окружение
* **Операционная система:** Windows 10 Pro 21H2
*  **IDE:** IntelliJ IDEA 2023.1.4 (Community Edition)
*  **Java:** OpenJDK 11

**Comment by KaterinaVoroshilova** [comment]
исправлено
