### ISSUE TITLE
нельзя совершить покупку на сумму равную сумме лимита

### ISSUE THREAD

**Issue by KaterinaVoroshilova** [KaterinaVoroshilova/JAVA-DIPLOM#3]
# Описание
При покупке на сумму, равной сумме лимита падает тест, метод pay у класса CreditAccount выдает false, вместо true

# Локация дефекта
https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/blob/a9d5f27f37c484918af6da10c2f2f1b2991e248c/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L45

# Шаги воспроизведения
1. Создать объект класса CreditAccount со значением поля initialBalance = 0, creditLimit - положительным, rate - неотрицательным
2. Запустить метод pay с параметром amount равным значению поля creditLimit.
3. Посмотреть на вывод в консоли
*Ожидаемый результат:* true (покупка совершена)
*Фактический результат:* false (покупка не совершена)

# Скриншот
![image](https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/assets/137503847/f047c0a1-70f3-4bda-8e44-a60bf89f7555)

# Тест
https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/blob/287ccdccbee6bdfeea7d8d52b650981051ed4f8b/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L94-L102

# Окружение
* **Операционная система:** Windows 10 Домашняя версия 22H2
* **IDE:** IntelliJ IDEA Community Edition 2023.1.4
* **Java:** OpenJDK 11.0.19
@gatsu00

**Comment by gatsu00** [comment]
Исправлено
