### ISSUE TITLE
После двух покупок баланс равен минус сумме последней покупки, а не двух вместе

### ISSUE THREAD

**Issue by KaterinaVoroshilova** [KaterinaVoroshilova/JAVA-DIPLOM#4]
# Описание
После двух покупок на суммы 2000 и 1000 и начальном балансе 0 баланс должен установиться -3000. Устанавливается по факту -1000

# Локация дефекта
https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/blob/d08513615762231bbb4cc68c0ee6cc8ca000d36d/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L45-L46

# Шаги воспроизведения
1. Создать объект класса CreditAccount со значением поля initialBalance = 0, creditLimit - 5000, rate - 15
2. Запустить метод pay с параметром amount равным 2000.
3. Запустить метод pay еще раз с параметром amount равным 1000.
4. Запросить баланс счета (getBalance).
5. Посмотреть на вывод в консоли

*Ожидаемый результат:* баланс равен -3000
*Фактический результат:* баланс равен -1000 

# Скриншот
![image](https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/assets/137503847/b20e6eb6-c74c-4fd2-9bd6-1ce72d14baaa)

# Тест
https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/blob/d08513615762231bbb4cc68c0ee6cc8ca000d36d/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L115-L127

# Окружение
* **Операционная система:** Windows 10 Домашняя версия 22H2
* **IDE:** IntelliJ IDEA Community Edition 2023.1.4
* **Java:** OpenJDK 11.0.19
@gatsu00

**Comment by gatsu00** [comment]
Исправлено
