### ISSUE TITLE
некорректный подсчет ставки

### ISSUE THREAD

**Issue by gatsu00** [KaterinaVoroshilova/JAVA-DIPLOM#40]
# Описание
При подсчёте ставки не высчитывает корректно

# Локация дефекта
https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/blob/d6f599636ba7bfb02e2c2dc2036ede561bbaf322/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L118-L121

# Шаги воспроизведения
1. Создать объект класса SavingAccount со следующими параметрами:
     SavingAccount account = new SavingAccount(
     99
     50
     6_000
     80
     );
2. Запустить метод yearChange:  Assertions.assertEquals(79, account.yearChange());
3. Посмотреть на вывод в консоли

*Ожидаемый результат:* 79
*Фактический результат:* 0

# Скриншот
![image](https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/assets/137397543/a9248632-2b82-4cba-8904-262846b6ae08)

# Тест
https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/blob/9989d5bbdd9facd8afe02192fa18d1f8d9d6b310/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L315-L325

# Окружение
* **Операционная система:** Windows 10 Pro 21H2
*  **IDE:** IntelliJ IDEA 2023.1.4 (Community Edition)
*  **Java:** OpenJDK 11

**Comment by KaterinaVoroshilova** [comment]
исправлено
