### ISSUE TITLE
Не учитывает начальный баланс при расчете баланса после покупки

### ISSUE THREAD

**Issue by KaterinaVoroshilova** [KaterinaVoroshilova/JAVA-DIPLOM#5]
# Описание
После покупки на сумму 2000  и начальном балансе 1000 баланс должен установиться -1000. Устанавливается по факту -2000

# Локация дефекта
https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/blob/d08513615762231bbb4cc68c0ee6cc8ca000d36d/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L45-L46

# Шаги воспроизведения
1. Создать объект класса CreditAccount со значением поля initialBalance = 1000, creditLimit = 5000, rate = 15
2. Запустить метод pay с параметром amount равным 2000.
4. Запросить баланс счета (getBalance).
5. Посмотреть на вывод в консоли

*Ожидаемый результат:* баланс равен -1000
*Фактический результат:* баланс равен -2000 

# Скриншот
![image](https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/assets/137503847/d1974b2b-8856-4413-b925-d29d576c64fa)

# Тест
https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/blob/d08513615762231bbb4cc68c0ee6cc8ca000d36d/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L129-L140

# Окружение
* **Операционная система:** Windows 10 Домашняя версия 22H2
* **IDE:** IntelliJ IDEA Community Edition 2023.1.4
* **Java:** OpenJDK 11.0.19
@gatsu00

**Comment by gatsu00** [comment]
Исправлено
