### ISSUE TITLE
Не учитывает начальный баланс при расчете конечного баланса после пополнения

### ISSUE THREAD

**Issue by KaterinaVoroshilova** [KaterinaVoroshilova/JAVA-DIPLOM#7]
# Описание
После пополнения на сумму 1 и начальном балансе 1 баланс должен установиться 2. Устанавливается по факту 1.

# Локация дефекта
https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/blob/d08513615762231bbb4cc68c0ee6cc8ca000d36d/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L65-L69

# Шаги воспроизведения
1. Создать объект класса CreditAccount со значением поля initialBalance = 1, creditLimit - 5000, rate - 15
2. Запустить метод add с параметром amount равным 1.
3. Запросить баланс счета (getBalance).
4. Посмотреть на вывод в консоли

*Ожидаемый результат:* баланс равен 2
*Фактический результат:* баланс равен 1

# Скриншот
![image](https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/assets/137503847/7fd5e585-945d-4d8d-9ab6-5827f7735452)

# Тест
https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/blob/d08513615762231bbb4cc68c0ee6cc8ca000d36d/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L189-L200

# Окружение
* **Операционная система:** Windows 10 Домашняя версия 22H2
* **IDE:** IntelliJ IDEA Community Edition 2023.1.4
* **Java:** OpenJDK 11.0.19
@gatsu00

**Comment by gatsu00** [comment]
Исправлено
