### ISSUE TITLE
Насчитывает годовые проценты при положительном балансе

### ISSUE THREAD

**Issue by KaterinaVoroshilova** [KaterinaVoroshilova/JAVA-DIPLOM#8]
# Описание
При положительном балансе сумма процентов должна приравниваться к 0. Здесь же метод yearChange рассчитывает сумму при положительном балансе

# Локация дефекта
https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/blob/d08513615762231bbb4cc68c0ee6cc8ca000d36d/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L81-L84

# Шаги воспроизведения
1. Создать объект класса CreditAccount со значением поля initialBalance = 0, creditLimit - 5000, rate - 15
2. Запустить метод add с параметром amount равным 200.

3, Запустить метод yearChange,
4. Посмотреть на вывод в консоли
Ожидаемый результат: 0
Фактический результат: 30

# Скриншот
![image](https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/assets/137503847/9c07ff16-143c-4da2-8d2e-91103d9709de)

# Тест
https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/blob/d08513615762231bbb4cc68c0ee6cc8ca000d36d/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L216-L227

# Окружение
* **Операционная система:** Windows 10 Домашняя версия 22H2
* **IDE:** IntelliJ IDEA Community Edition 2023.1.4
* **Java:** OpenJDK 11.0.19
@gatsu00

**Comment by gatsu00** [comment]
Исправлено
