### ISSUE TITLE
Отсутствие исключения при minBalance, превышающем maxBalance

### ISSUE THREAD

**Issue by gatsu00** [KaterinaVoroshilova/JAVA-DIPLOM#9]
# Описание
В данном коде отсутствует проверка, если значение minBalance больше значения maxBalance. Объект сберегательного счета может быть создан с некорректными параметрами, что может привести к неправильной работе системы или ошибкам в дальнейшем использовании этого объекта.

# Локация дефекта
https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/blob/e586503fa99cdd2cb60383fdf80304abc0fbd9e4/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22-L32

# Шаги воспроизведения
1. Создать объект класса SavingAccountTest с значениями minBalance превышающих maxBalance 
1. Запустить в программу
1. Посмотреть на вывод в консоли

*Ожидаемый результат:* Вывод сообщения:  "Минимальный баланс не может быть больше максимального баланса"
*Фактический результат:* Тест прерывается с сообщением об ошибке в консоли

# Скриншот
![image](https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/assets/137397543/5185449e-b97c-48e9-a9b8-58dbd5593b14)

# Тест
https://github.com/KaterinaVoroshilova/JAVA-DIPLOM/blob/e3967e4e4b6f9f5d1f4e7d38304e80cb3140eced/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L64-L72

# Окружение
 * **Операционная система:** Windows 10 Pro 21H2
* **IDE:** IntelliJ IDEA 2023.1.4 (Community Edition)
* **Java:** OpenJDK 11
@KaterinaV

**Comment by KaterinaVoroshilova** [comment]
исправлено
